### ISSUE TITLE
amo/chats_wallpaper.user.js : не видны приглашения в чат на темных фонах.

### ISSUE THREAD

**Issue by nzhirkovAMO** [dnklhtbgn/user-js-and-css#1]
Подложечку бы добавить((
![image](https://github.com/dnklhtbgn/js-user-scripts/assets/137226071/29269edb-b011-47be-bb81-f09634ab2031)

**Comment by dnklhtbgn** [comment]
Подложечки не сделал, но добавил в скрипты для amo мессенджера темную тему, теоретически должно помочь с читаемостью ссылок на пользователей и прочих сервисных сообщений
