### ISSUE TITLE
В темной теме amo теряются знаки прочитанных сообщений

### ISSUE THREAD

**Issue by nzhirkovAMO** [dnklhtbgn/user-js-and-css#2]
![image](https://github.com/dnklhtbgn/user-js-and-css/assets/137226071/907ab7b2-e8e9-4da2-8f43-e4a79e741899)

Т.к. в темной теме преобладают именно синие тона, то значок прочитанного сообщения (двойная голубая галочка) теряется на синем фоне. Есть ли возможность перекрасить ее? Например в белый.

**Comment by dnklhtbgn** [comment]
Исправлено в версии 0.5

**Comment by nzhirkovAMO** [comment]
Спасибо
