### ISSUE TITLE
В темной теме amo ломается отображение сообщения к ответу во время написания текста

### ISSUE THREAD

**Issue by nzhirkovAMO** [dnklhtbgn/user-js-and-css#3]
![image](https://github.com/dnklhtbgn/user-js-and-css/assets/137226071/c1a29a44-ad8d-4b21-a292-260cdf1254ce)
Ну, тут просто и понятно

**Comment by nzhirkovAMO** [comment]
В добавок: 
![image](https://github.com/dnklhtbgn/user-js-and-css/assets/137226071/324dc23b-587b-47c2-95e2-db012038ee91)
Подсветка найденного сообщения и цвет текста в строке поиска по сообщениям

**Comment by dnklhtbgn** [comment]
Отображение сообщения при ответе на него поправил, с поиском сообщений пока не разобрался

**Comment by dnklhtbgn** [comment]
Исправлено в версии 0.5
