### ISSUE TITLE
Темный цвет шрифта в заголовке названия папки

### ISSUE THREAD

**Issue by bmoiseenko** [dnklhtbgn/user-js-and-css#4]
![Снимок экрана от 2023-07-28 12-39-50](https://github.com/dnklhtbgn/user-js-and-css/assets/113043126/5c34c531-829f-402f-8aa3-f89855bcd821)
Скорее всего, просто не изменен цвет заголовка, берется дефолтный

**Comment by dnklhtbgn** [comment]
В принципе поправил отображение папок с диалогами в темной теме
